# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: media_timeline_development
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: media_timeline_production
  username: root
  password: nerRTn0e(SWvCezwG5^UeHmeYkklXw
